// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.subsystems.*;
import frc.robot.RobotContainer;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.I2C; //not sure if I need this. This is for the port
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.util.Color;
import edu.wpi.first.wpilibj.*;

import com.ctre.phoenix.motorcontrol.NeutralMode;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


public class ControlPanel implements Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private WPI_TalonSRX controlPanelMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
   private String currentColor = "Unknown";
  private String temp = "Unknown";
  private int ctr = 0;
  private double confidences;

  
    public ControlPanel() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    controlPanelMotor = new WPI_TalonSRX(7);


        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

 
    

    @Override
    public void periodic() {
       

        // Put code here to be run every loop
  }
  public void run(double pow) {    	
    controlPanelMotor.set(pow);
}
public void stop(){
  controlPanelMotor.set(0);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
}

public void rotateX(ColorSensor m_colorSensor) {
  SmartDashboard.putNumber("Counter", ctr);
  currentColor = m_colorSensor.getColorString();
  confidences = m_colorSensor.getConfidence();
  //System.out.println(confidences);
  
  //while (ctr<16){
    if (ctr<26){
      controlPanelMotor.set(0.5);
    }

    //System.out.println("TEMP:" + temp + temp + temp + temp + temp);
    //System.out.println("CURRENT:" + currentColor + currentColor + currentColor + currentColor + currentColor);
    //System.out.println("Check:" + ctr);
    //System.out.println("Confidence " + confidences);

    //everytime the color changes counter goes up
    if (currentColor!= temp && confidences>.935) {
      ctr++;
      temp = currentColor;
      
      
    }
}
public void rotateColor(Color desiredColor, ColorSensor colorSensor){
  Color currentColor = colorSensor.getColor();
  confidences = colorSensor.getConfidence();
  if(!desiredColor.equals(currentColor) && confidences>.8){ 
    controlPanelMotor.set(.5);
  }
  
}
public int getCounter(){
  return ctr;
}
public void setCounter(int counter){
  ctr = counter;
}
public void setBrakeMode(){
  controlPanelMotor.setNeutralMode(NeutralMode.Brake);
  }
  public void setCoastMode(){
  controlPanelMotor.setNeutralMode(NeutralMode.Coast);
  }


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}


