// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.Solenoid;


public class Cooling implements Subsystem {

    private Solenoid coolingSolenoid;
    private Drivetrain m_drivetrain;
    private Shooter m_shooter;

    public Cooling(Drivetrain drivetrain, Shooter shooter) {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    coolingSolenoid = new Solenoid(0, 0);
    m_drivetrain = drivetrain;
    m_shooter = shooter;
    setDefaultCommand(new Cool(this));
    coolingSolenoid.set(false);

    }
    
    @Override
    public void periodic() {
        
       
    }
    public void cool()
    {
        SmartDashboard.putBoolean("Shooter Temp", m_shooter.checkTemp());
        if (m_drivetrain.checkTemp() || m_shooter.checkTemp())
            coolingSolenoid.set(true);
        else
            coolingSolenoid.set(false);

    }


}

