// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj.Solenoid;

/**
 *
 */
public class Stopper implements Subsystem {     
    private Solenoid stopperSolenoid;
    private boolean m_in;
    public Stopper() {
        stopperSolenoid = new Solenoid(0,2);
        m_in = true;
        stopperSolenoid.set(m_in);
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void openStopper(){
        m_in = false;
        stopperSolenoid.set(m_in);
    }

    public void closeStopper(){
        m_in = true;
        stopperSolenoid.set(m_in);
    }

    public boolean isIn(){
        return m_in;
    }

    public String toString(){
        if(m_in) return "Stopper is in";
        else return "Stopper is out";
    }

    public boolean ballSensedOut(){
        return true;
    }
}
