// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import frc.robot.Robot;
import frc.robot.subsystems.Drivetrain;

public class InvertDrive extends InstantCommand {

    private final Drivetrain m_subsystem;
    public InvertDrive(Drivetrain subsystem) {
        m_subsystem = subsystem;
        addRequirements(subsystem);

    }

    // Called once when this command runs
    @Override
    public void initialize() {
        if(m_subsystem.getReversed()==false)
        {
            m_subsystem.setReversed(true);
        }
        else
        {
            m_subsystem.setReversed(false);
        }
    }

}
