// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import frc.robot.Robot;
import frc.robot.subsystems.Drivetrain;

public class InvertDrive extends InstantCommand {

    private final Drivetrain m_subsystem;
    public InvertDrive(Drivetrain subsystem) {
        m_subsystem = subsystem;
        //FIXME: As this is instantaneous and only toggles a boolean (not "controlling" the subsystem), don't have it require the drivetrain.
        // Otherwise, this will take over the drivetrain and TankDrive.end() will be called for 1 "frame", causing a stutter.
        addRequirements(subsystem);

    }

    // Called once when this command runs
    @Override
    public void initialize() {
        //FIXME: getReversed() returns a boolean. You don't need an if-statement...
        // Just do (pseudocode):
        // isReversed = getReversed()
        // setReversed(!isReversed)
        if(m_subsystem.getReversed()==false)
        {
            m_subsystem.setReversed(true);
        }
        else
        {
            m_subsystem.setReversed(false);
        }
    }

}
