// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj2.command.CommandBase;

//import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.Robot;
//import frc.robot.subsystems.ColorSensor;
import frc.robot.subsystems.ControlPanel;

import com.revrobotics.ColorMatch;

/**
 *
 */
public class RotationControl extends CommandBase {
    private final ControlPanel m_controlPanel;
   

   
    public RotationControl(ControlPanel controlPanel) {
        m_controlPanel = controlPanel;
   
        addRequirements(controlPanel);

   
    }

    // Called just before this Command runs the first time
    @Override
    public void initialize() {
        m_controlPanel.setCounter(0);

    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    public void execute() {
        m_controlPanel.rotateX();
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    public boolean isFinished() {
        if (m_controlPanel.getCounter()>26) return true;
        return false;
    }

    // Called once after isFinished returns true
    @Override
    public void end(boolean interrupted) {
        m_controlPanel.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    
}
