// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.Robot;
import frc.robot.subsystems.Turret;

/**
 *
 */
public class RunTurretVision extends CommandBase {
    private static final double ALIGNMENT_RANGE_INNER = 3;
    private static final double ALIGNMENT_RANGE_OUTER = 10;

    private double[] visionResults;
    private double horizontalAngle;
    private double verticalAngle;
    private double alignmentAngle;
    private double distance;
    private final Turret m_turret;
    
    public RunTurretVision(Turret turret) {
        m_turret = turret;
        addRequirements(m_turret);
    }

    // Called just before this Command runs the first time
    @Override
    public void initialize() {
        visionResults = new double[] {0, 0};
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    public void execute() {
        // Result key:
        //  0. timestamp
        //  1. success (0/1)
        //  2. distance
        //  3. horizontal angle
        //  4. vertical angle
        //  5. alignment angle
        //  6. inner port (0/1)
        //  7. instantaneous FPS
        visionResults = SmartDashboard.getNumberArray("Vision/result", new double[] {0, 0});
        if (visionResults[1] == 0) {
            m_turret.status = "none";
            SmartDashboard.putString("Vision/valid_shot", m_turret.status);
            return;
        }

        distance = visionResults[2];
        horizontalAngle = visionResults[3];
        verticalAngle = visionResults[4];
        alignmentAngle = visionResults[5];

        m_turret.setHorizontalAngleRelative(horizontalAngle);
        m_turret.setVerticalAngle(verticalAngle);

        if (m_turret.atHorizontalAngle(horizontalAngle) && m_turret.atVerticalAngle(verticalAngle)) {
            // if (alignmentAngle < ALIGNMENT_RANGE_INNER) {
            //     SmartDashboard.putString("Vision/valid_shot", "inner");
            // } else if (alignmentAngle < ALIGNMENT_RANGE_OUTER) {
            //     SmartDashboard.putString("Vision/valid_shot", "outer");
            // } else {
            //     SmartDashboard.putString("Vision/valid_shot", "locked but none");
            // }
            m_turret.status = "locked";
            SmartDashboard.putString("Vision/valid_shot", m_turret.status);
        } else {
            m_turret.status = "homing";
            SmartDashboard.putString("Vision/valid_shot", m_turret.status);
        }
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    public boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    public void end(boolean interrupted) {
        m_turret.setHorizontalAngleAbsolute(0);
        SmartDashboard.putBoolean("Vision/error", false);
    }
}
