// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import frc.robot.Robot;
import frc.robot.RobotContainer;
import frc.robot.subsystems.Drivetrain;

/**
 *
 */
public class ToggleLockStraight extends CommandBase {

    private final Drivetrain m_subsystem;
    public ToggleLockStraight(Drivetrain subsystem) {

        m_subsystem = subsystem;
        addRequirements(subsystem);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    public void initialize() {
        m_subsystem.setPercentVBus();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    public void execute() {
        double leftSpeed, rightSpeed, avgSpeed;
        rightSpeed = -RobotContainer.rightJoystick.getY();
        leftSpeed = -RobotContainer.leftJoystick.getY();
        avgSpeed = (rightSpeed + leftSpeed) / 2;
        //FIXME: Use better names for smartdashboard keys
        // Would strongly recommend starting with class name. IE: DriveTrain left speed set
        // Prevents key collision and helps speed up debugging
        SmartDashboard.putNumber("RightSpeed: ", rightSpeed);
        SmartDashboard.putNumber("LeftSpeed: ", leftSpeed);
        SmartDashboard.putNumber("AvgSpeed: ", avgSpeed);
        m_subsystem.run(avgSpeed, avgSpeed);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    public boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    public void end(boolean interrupted) {
        m_subsystem.stop();
    }
}

