// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import java.security.PublicKey;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.Shifters;
import frc.robot.subsystems.Turret;
import frc.robot.Robot;

/**
 *
 */
public class TurretToZero extends CommandBase {

    
    private final Turret m_turret;
    private boolean done;

    public TurretToZero(Turret turret) {
        m_turret = turret;
        // Use addRequirements() here to declare subsystem dependencies.
        addRequirements(m_turret);
      }

    // Called just before this Command runs the first time
    @Override
    public void initialize() {
        done = false;
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    public void execute() {
        done = m_turret.runHorizontalManual(0);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    public boolean isFinished() {
        return done;
    }

    // Called once after isFinished returns true
    @Override
    public void end(boolean interrupted) {
        m_turret.stopHorizontal();
    }
}
